// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// BDSim
Rcpp::List BDSim(const int& nrep, const int& tend, const Rcpp::List& parslist, int setthreads, bool progressbar);
RcppExport SEXP _pkgIntrogression_BDSim(SEXP nrepSEXP, SEXP tendSEXP, SEXP parslistSEXP, SEXP setthreadsSEXP, SEXP progressbarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type nrep(nrepSEXP);
    Rcpp::traits::input_parameter< const int& >::type tend(tendSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type parslist(parslistSEXP);
    Rcpp::traits::input_parameter< int >::type setthreads(setthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type progressbar(progressbarSEXP);
    rcpp_result_gen = Rcpp::wrap(BDSim(nrep, tend, parslist, setthreads, progressbar));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pkgIntrogression_BDSim", (DL_FUNC) &_pkgIntrogression_BDSim, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_pkgIntrogression(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
