# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BDSim <- function(nrep, tend, parslist, setthreads = 0L, progressbar = TRUE) {
    .Call(`_pkgIntrogression_BDSim`, nrep, tend, parslist, setthreads, progressbar)
}

